services: 
  back-end:
    build: 
      context: backend 
    container_name: back-end
    working_dir: /src/
    networks: 
      - node-network
    volumes: 
      - ./backend:/src/
      - /src/node_modules
    tty: true
    ports: 
      - "3000:3000"
    command: node ./app.js 
  front-end:
    build: 
      context: frontend 
    container_name: front-end
    working_dir: /src/
    networks: 
      - node-network
    volumes: 
      - ./frontend:/src/
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "5173:5173"
    command: npm run dev -- --host

networks: 
  node-network:
    driver: bridge    
